# Generated by Django 6.0 on 2025-12-04 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='Supabase Auth User ID')),
                ('type', models.CharField(choices=[('CHANNEL', 'Channel'), ('PLAYLIST', 'Playlist')], default='CHANNEL', max_length=20)),
                ('youtube_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('sync_frequency', models.CharField(default='daily', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ERROR', 'Error'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'status'], name='core_source_user_id_e58985_idx')],
                'unique_together': {('user_id', 'youtube_id')},
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('transcript_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ai_analysis_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.source')),
            ],
            options={
                'indexes': [models.Index(fields=['source', '-published_at'], name='core_video_source__253b6b_idx')],
            },
        ),
    ]
