# Generated by Django 6.0 on 2025-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
