# Generated by Django 6.0 on 2025-12-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_sync', '0002_video_transcript_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Last processing error message', null=True),
        ),
    ]
