# Generated by Django 6.0 on 2025-12-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_sync', '0003_video_processing_error'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='source',
            new_name='yt_sync_sou_user_id_0cdcae_idx',
            old_name='yt_sync_source_user_id_e58985_idx',
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='yt_sync_vid_source__c6d4a3_idx',
            old_name='yt_sync_video_source__253b6b_idx',
        ),
    ]
